sudo: required
services:
  - docker

before_install:
  - docker build -t aidenlambert94/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aidenlambert94/docker-react npm run test -- --coverage
